### ISSUE TITLE
yazi, a file explorer

### ISSUE THREAD

**Issue by JinEnMok** [unpluggedcoder/awesome-rust-tools#11]
From their blurb: 

> Yazi (means "duck") is a terminal file manager written in Rust, based on non-blocking async I/O. It aims to provide an efficient, user-friendly, and customizable file management experience.

Got both a [repo](https://github.com/sxyazi/yazi?tab=readme-ov-file) and a [website](https://yazi-rs.github.io/)

**Comment by unpluggedcoder** [comment]
Added. Thanks.
